version: '2'

tasks:
  run:
    cmds:
      - go run -ldflags "-X main.GitCommit=$EMPLIDLER_GIT_COMMIT -X main.ServerUrl=$EMPLIDLER_SERVER_URL -X main.AppKey=$EMPLIDLER_APP_KEY" .
    env:
      EMPLIDLER_GIT_COMMIT:
        sh: git describe --tag

  build:
    cmds:
      - mkdir -p build/bin
      - go build -ldflags "-X main.GitCommit=$EMPLIDLER_GIT_COMMIT -X main.ServerUrl=$EMPLIDLER_SERVER_URL -X main.AppKey=$EMPLIDLER_APP_KEY" -o build/bin/emplidler .
    silent: true
    vars:
      EMPLIDLER_GIT_COMMIT:
        sh: git describe --tag

  package:
    cmds:
      - mkdir -p release/Emplidler.app/Contents/MacOS
      - mkdir -p release/Emplidler.app/Contents/Resources
      - cp assets/darwin/Info.plist release/Emplidler.app/Contents/Info.plist
      - cp assets/darwin/icon.icns release/Emplidler.app/Contents/Resources/icon.icns
      - cp build/bin/emplidler release/Emplidler.app/Contents/MacOS/emplidler
    silent: true

  clean:
    cmds:
      - rm -rf build release

  release:
    cmds:
      - task: build
      - task: package
